import pymysql


db=pymysql.connect("localhost","root","","samplefamily",charset="UTF8")
cursor=db.cursor()
cursor.execute("DROP TABLE IF EXISTS virus_family")
sql="""CREATE TABLE virus_family (
         Sample_HASH  CHAR(100) NOT NULL,
         ALYac  CHAR(50),
        APEX  CHAR(50),
AVG  CHAR(50),
Acronis  CHAR(50),
Ad_Aware  CHAR(50),
AegisLab  CHAR(50),
AhnLab_V3  CHAR(50),
Alibaba  CHAR(50),
Antiy_AVL  CHAR(50),
Arcabit  CHAR(50),
Avast  CHAR(50),
Avast_Mobile  CHAR(50),
Avira  CHAR(50),
Babable  CHAR(50),
Baidu  CHAR(50),
BitDefender  CHAR(50),
Bkav  CHAR(50),
CAT_QuickHeal  CHAR(50),
CMC  CHAR(50),
ClamAV  CHAR(50), 
Comodo  CHAR(50),
CrowdStrike  CHAR(50),
Cybereason  CHAR(50),
Cylance  CHAR(50),
Cyren  CHAR(50),
DrWeb  CHAR(50),
ESET_NOD32  CHAR(50),
Emsisoft  CHAR(50),
Endgame  CHAR(50),
F_Prot  CHAR(50),
F_Secure  CHAR(50),
FireEye  CHAR(50),
Fortinet  CHAR(50),
GData  CHAR(50),
Ikarus  CHAR(50),
Invincea  CHAR(50),
Jiangmin  CHAR(50),
K7AntiVirus  CHAR(50),
K7GW  CHAR(50),
Kaspersky  CHAR(50),
Kingsoft  CHAR(50),
MAX  CHAR(50),
Malwarebytes  CHAR(50),
MaxSecure  CHAR(50),
McAfee  CHAR(50),
McAfee_GW_Edition  CHAR(50),
MicroWorld_eScan  CHAR(50),
Microsoft  CHAR(50),
NANO_Antivirus  CHAR(50),
Paloalto  CHAR(50),
Panda  CHAR(50),
Qihoo_360  CHAR(50),
Rising  CHAR(50),
SUPERAntiSpyware  CHAR(50),
SentinelOne  CHAR(50),
Sophos  CHAR(50),
Symantec  CHAR(50),
SymantecMobileInsight  CHAR(50),
TACHYON  CHAR(50),
Tencent  CHAR(50),
TotalDefense  CHAR(50),
Trapmine  CHAR(50),
TrendMicro  CHAR(50),
TrendMicro_HouseCall  CHAR(50),
Trustlook  CHAR(50),
VBA32  CHAR(50),
VIPRE  CHAR(50),
ViRobot  CHAR(50),
Webroot  CHAR(50),
Yandex  CHAR(50),
Zillya  CHAR(50),
ZoneAlarm  CHAR(50),
Zoner  CHAR(50))"""

cursor.execute(sql)
db.commit()
db.close()